name: "Pogoda"

on:
  workflow_dispatch:
    inputs:
      city:
        description: "Miasto"
        required: true
        default: "Sieradz"

jobs:
  pogoda_dla_miast:
    name: "Pogoda dla miast"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Run script"
        run: |
          echo "Pogoda dla miasta: ${{ github.event.inputs.city }}" >> $GITHUB_STEP_SUMMARY
          echo "${{ secrets.api_key }}" >> temp_file
          cat temp_file
          bash ./start.sh "${{ github.event.inputs.city }}" "${{ secrets.api_key }}" >> $GITHUB_STEP_SUMMARY
